"ba_jail_dubai"
 {
     "name"              "ba_jail_dubai"
     "minplayers"        "1"
     "maxplayers"        "40"
     "extraspectators"   "5"
     "imagename"         "map-dust2-overall"
     "t_arms"            "models/weapons/t_arms_professional.mdl"
     "ct_arms"           "models/weapons/ct_arms_swat.mdl"
     "t_models"
     {
         "tm_professional_var1"      ""
         "tm_professional_var2"      ""
         "tm_professional_var3"      ""
         "tm_professional_var4"      ""
         "tm_professional"      ""
     }
     "ct_models"
     {
         "ctm_swat"       ""
         "ctm_swat_varianta"  ""
         "ctm_swat_variantb"  ""
         "ctm_swat_variantc"  ""
         "ctm_swat_variantd"  ""
     }
 }