/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>

#define ssg08Speed 1.2
#define ssg08Gravity 0.2

public Plugin:myinfo = 
{
	name = "Custom Speed & Gravity for SSG08",
	author = "apocalyptic /Edit by, Mester Skunk",
	description = "gives player your custom speed and gravity when he is holding a knife",
	version = "1.0",
	url = "<- URL ->"
}

public OnClientPutInServer(client) 
{ 
	SDKHook(client, SDKHook_WeaponSwitchPost, OnWeaponSwitchPost) 
} 

public OnClientDisconnect(client) 
{ 
	SDKUnhook(client, SDKHook_WeaponSwitchPost, OnWeaponSwitchPost) 
}  

public OnWeaponSwitchPost(client, weapon) 
{
	new String:Wpn[24] 
	GetClientWeapon(client,Wpn,24)
	if (StrEqual(Wpn,"weapon_ssg08"))
	{
		SetClientSpeed(client,ssg08Speed)
		SetEntityGravity(client,ssg08Gravity)
	}
	else
	{
		SetClientSpeed(client,1.0)
		SetEntityGravity(client,1.0)
	}
} 

public SetClientSpeed(client,Float:speed) 
{ 
	SetEntPropFloat(client, Prop_Send, "m_flLaggedMovementValue",speed)
}  