/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>

#define KnifeSpeed 1.6
#define KnifeGravity 0.5

#define ssg08Speed 1.2
#define ssg08Gravity 0.15

public Plugin:myinfo = 
{
	name = "Specifik Speed & Gravity per Weapon",
	author = "Mester Skunk",
	description = "gives player your custom speed and gravity when he is holding a knife",
	version = "1.0",
	url = "<- URL ->"
}

public OnClientPutInServer(client) 
{ 
	SDKHook(client, SDKHook_WeaponSwitchPost, OnWeaponSwitchPost) 
} 

public OnClientDisconnect(client) 
{ 
	SDKUnhook(client, SDKHook_WeaponSwitchPost, OnWeaponSwitchPost) 
}  

public OnWeaponSwitchPost(client, weapon) 
{
	new String:Wpn[24] 
	GetClientWeapon(client,Wpn,24)
	if (StrEqual(Wpn,"weapon_ssg08"))
	{
		SetClientSpeed(client,ssg08Speed)
		SetEntityGravity(client,ssg08Gravity)
	}
	else if (StrEqual(Wpn,"weapon_knife"))
	{
		SetClientSpeed(client,KnifeSpeed)
		SetEntityGravity(client,KnifeGravity)
	}
	else
	{
		SetClientSpeed(client,1.0)
		SetEntityGravity(client,1.0)
	}
} 

public SetClientSpeed(client,Float:speed) 
{ 
	SetEntPropFloat(client, Prop_Send, "m_flLaggedMovementValue",speed)
}  